name: Prove

on:
  workflow_call:
    inputs:
      # working-directory is added to accommodate monorepo.  For multi repo, defaults to '.', current directory
      working-directory:
        required: false
        type: string
        default: '.'
      build-pl-args:
        required: false
        type: string
        default: ''
      build-pl-test-args:
        required: false
        type: string
        default: ''
      prepend-perl5lib-env:
        required: false
        type: string
        default: ''

jobs:
  prove:
    runs-on: ubuntu-latest
    # accommodating monorepo, this sets the working directory at the job level, for multi repo, defaults to "."
    defaults:
      run:
        working-directory: "${{ inputs.working-directory }}"

    # run release flow only if the triggering branch starts with "release/"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies with cpanm
        uses: registry.opensuse.org/home/josegomezr/perl-toolkit/containers-tw/tester-perl:latest
        with:
          args: |
            if [[ -f cpanfile ]]; then
              cpanm --installdeps . --with-develop --notest
            fi

      - name: Run Prove
        uses: registry.opensuse.org/home/josegomezr/perl-toolkit/containers-tw/tester-perl:latest
        with:
          args: |
            ADDITIONAL_PER5LIB="${{ inputs.prepend-perl5lib-env }}"

            if [[ "x$ADDITIONAL_PER5LIB" != "x" ]]; then
              export PERL5LIB="${ADDITIONAL_PER5LIB}:${PERL5LIB}"
            fi

            perl Build.PL ${{ inputs.build-pl-args }}
            ./Build test ${{ inputs.build-pl-test-args }}
